# -*- coding: utf-8 -*-
"""370_Mod_4_In_Class.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jSD_gn-Krv1spiBroxITvhv8DZ5VgnU-

Title: Analyzing cunsumer data
Description: A project to learn and practice some additional dataframe and pandas skills.
Created by Jalyn Buthman
"""

import pandas as pd

cd = pd.read_csv("/content/ConsumerData.csv")

print(cd.head())
print()

print(cd.info())
print()
#objects are strings in the data types

print(cd.describe())
print()

#use .unique to view all of the options for marital status and education
print(cd["Marital_Status"].unique())
print()

print(cd["Education"].unique())
print()

#print the number of unique entries
print(cd.nunique())
print()

#a column can be referred to as a series
#create an age series and add it to the df
cd['Age'] = 2024 - cd['Year_Birth']
print(cd.head)
print()

#print the descrptive statics of the new age column
print(cd['Age'].describe())
print()

#create and incomeratio series and add it to the df
cd['Income_Ratio'] = cd['Income']/cd['Age']
print(cd['Income_Ratio'].describe())
print()

#convert a date string (dt_customer) to a date data type
#you must specify the format of the date, otherwise it will be different than the rest of the dataset
cd['Cust_Datetime'] = pd.to_datetime(cd['Dt_Customer'], format= '%m/%d/%Y')
print(cd.info())
print()

#drop the kidhome and teenhome columns by creating a copy of the dataframe without those columns
#you do not need cd within the parenthesis below because cd is already specified
#axis = 1 specifies that we are dropping a column, = 0 specifies dropping a row
cd_new = cd.drop(['Kidhome', 'Teenhome'], axis = 1)
print(cd_new.head())
print()

"""Three insights from descriptive statistics of the data.
1. The mean income is $43,923
2.The maximum year of birth is 1989
3.The minimum year of birth is 1946

"""