# -*- coding: utf-8 -*-
"""370_Mod_2_Videos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y74zN13cn3oiGQW9-Cu6pJ9JhZL_8kfF

Title: Mod 2 Code Examples
This code covers formatted strings, for loops, the range functions, and dictionaries.
"""

#formatted strings
name = "Jolena"
age = 30

message = f"Hello my name is {name} and I am {age} years old"
print (message)

print(f"The result of 2+2 is {2+2}.")

#for loops
#for VARIABLE in SEQUENCE:
  #code to repeat in the for loop.

#calculate total sales
#list of daily sales for each product
daily_sales = [1500, 2000, 2200, 1600]

#initialize total_sales to o
total_sales = 0

#using a for loop to iterate over the daily_sales list
for sales in daily_sales:
  total_sales += sales

#printing total sales
print(f"Total sales for the day: ${total_sales:,.2f}")

#range() function

#for VARIABLE in range(START, STOP, STEP):
  #START is optional, without it will default to 0
  #STOP is required, the program will stop 1 number before the stop value
  #STEP is the inciment between values, it is optional and defaults to 1

#using range in a for loop to print numbers from 1 to 5
for num in range(1,6):
  print(num)

print()

for num in range(6):
  print(num)

print()

for num in range (0,7,2):
  print(num)

#dictionaries
employee = {
    'name': 'John Doe',
    'age': 30,
    'position': 'software engineer',
    'salary': 80000
}

#accessing the values using keys
print(f"Name: {employee['name']}")

#add five years to age
employee['age'] += 5
print(f"Age: {employee['age']}")

#update employee age to a new value
employee['age'] = 32
print(f"Age: {employee['age']}")

#Add department to employee dictionary
employee['department'] = 'Information Systems'
print(f"Department: {employee['department']}")