# -*- coding: utf-8 -*-
"""370_Mod_2_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WzQRktf16NnAejT2vwK0GNFwS3IaKN-h
"""

#dictionary within dictionary to keep track of book inventory
book_inventory = {'isbn34': {'title': 'Dracula',
                    'quantity': 110,
                    'price': 15
                    },
         'isbn35': {'title': 'Frankenstein',
                    'quantity': 80,
                    'price': 12.49
                    },
         'isbn36':{'title': 'War and Peace',
                   'quantity': 50,
                   'price': 23.99
                    }}

#for loop to simulate sales
for value in range(1,6):
  for key in book_inventory.keys():
    book_inventory[key]['quantity'] -= 5

#for loop to simulate restocking
for value in range(1,4):
  for key in book_inventory.keys():
    book_inventory[key]['quantity'] += 5

#for loop to display updated book inventory
print()
print(f"Updated Book Inventory Summary\n")
for key, value in book_inventory.items():
  print(f"ID: {key}")
  print(f"Title: {value['title']}")
  print(f"Price: ${value['price']:,.2f}")
  print(f"Quantity in stock: {value['quantity']}")
  print()