# -*- coding: utf-8 -*-
"""370_Mod_8_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A1o_Wna60saKpMf2i9SBnKaZXgJh_ZKF

Group Comparisons - Consumers

Jalyn Buthman
"""

import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats

df = pd.read_csv("/content/consumer_income.csv")

#print the descriptive statistics of the dataframe
print('The descriptive statistics for the full dataset: ')
print(df.describe())
print()

#print the info for the dataframe
print(df.info())
print()

#find the rows with missing data
print('Rows with missing data: ')
print(df.loc[df.isnull().any(axis=1)])

#remove the records with missing data using .drop
income = df.drop([10, 27, 43, 48, 58, 71, 90, 91, 92, 128, 133, 312, 319, 1379, 1382, 1383, 1386, 2059, 2061, 2078, 2079, 2081, 2084, 2228])

#create a subset for married customers and print the descriptive statistics
subsetm = income.loc[(income['Marital_Status'] == 'Married')]
print('The descriptive statistics for a subset of the dataframe that only includes married customers: ')
print(subsetm.describe())
print()

#create a subset for single customers and print the descriptive statistics
subsets = income.loc[(income['Marital_Status'] == 'Single')]
print('The descriptive statistics for a subset of the dataframe that only includes single customers: ')
print(subsets.describe())
print()





#create a box plot comparing income for married vs single customers
fig1, ax1 = plt.subplots()
ax1.set_title('Income for Married vs Single Customers')
ax1.boxplot([subsetm['Income'], subsets['Income'].values])
ax1.set_ylabel('Income ($)')
ax1.set_xticklabels(['Married Customers', 'Single Customers'])
plt.show
print()


#income
#hypothesis for the income of married vs single customers
print('H0: There is no significant difference in income between married and single customers.')
print('H1: There is a significant difference in income between married and single customers.')
print()
#t-tests for income
print('T-test results for difference in income between married and single customers(using a 0.05 significance level): ')
print(scipy.stats.ttest_ind(subsetm['Income'], subsets['Income']))
print()
#print the interpretations and concluions
print('Conclusion: Reject the null hypothesis and conclude that there is a significant difference in the income of\n            married customers compared to single customers.')
print()
print()
print()


#children
#hypothesis for the number of children at home for married vs single customers
print('H0: There is no significant difference in number of children at home between married and single customers.')
print('H1: There is a significant difference in number of children at home between married and single customers.')
print()
#t-tests for number of children at home
print('T-test results for difference in number of children at home between married and single customers(using a 0.05 significance level): ')
print(scipy.stats.ttest_ind(subsetm['Kidhome'], subsets['Kidhome']))
print()
#print the interpretations and concluions
print('Conclusion: Reject the null hypothesis and conclude that there is a significant difference in the number of\n            children that married customers have at home compared to the number of teens that single customers have at home.')
print()
print()
print()


#teens
#hypothesis for the number of teens at home for married vs single customers
print('H0: There is no significant difference in number of teens at home between married and single customers.')
print('H1: There is a significant difference in number of teens at home between married and single customers.')
print()
#t-tests for number of teens at home
print('T-test results for difference in in number of teens at home between married and single customers(using a 0.05 significance level): ')
print(scipy.stats.ttest_ind(subsetm['Teenhome'], subsets['Teenhome']))
print()
#print the interpretations and concluions
print('Conclusion: Fail to reject the null hypothesis and conclude that there is not a significant difference in the number of\n            teens that married customers have at home compared to the number of teens that single customers have at home.')
print()
print()
print()