# -*- coding: utf-8 -*-
"""370_Mod1_InClass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11XAYNHF11RxN13IMmulGtfaD-Fg5ujkJ

Jalyn Buthman
Mod 1 In-Class Project
"""

menu_items = {"Burgers": 9.00, "Fries": 3.50, "Drinks": 2.50}
tax_rate = 0.08
service_fee = 0.01

total_bill = 0
tax = 0

for items in menu_items:
  quantity = int(input(f"How many {items} would you like? "))
  item_price = menu_items[items]
  total_item_cost = quantity * item_price
  total_bill += total_item_cost
  tax = total_bill * tax_rate
  service = total_bill * service_fee
  final_bill = tax + service + total_bill
print (f'\nBurger Place Bill\n\nTotal Item Cost: ${total_bill:.2f}\nTaxes: ${tax:.2f}\nService Fee: ${service:.2f}\nTotal bill: ${final_bill:.2f}')