# -*- coding: utf-8 -*-
"""370_Mod_6_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MIZuVJPK2JEc2caRY9yn2upPV-qIdxF7
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
from numpy import median

#read in the dataset and print the header
tips = pd.read_csv("/content/tips.csv")
print(tips.head())
print()

#print the descriptive statistics
print(tips.describe())
print()

#print a histogram showing the distribution of tips
plt.hist(tips['tip'], bins = 10, rwidth=.9)
plt.title('Distribution of Tips Given to Servers')
plt.ylabel('Frequency')
plt.xlabel('Dollar amount of tip')
plt.show()
print()

#print a bar plot showing the relationship between day of the week and tip amount
p = sns.barplot(data = tips, x= 'day', y= 'tip', estimator = median)
p.set(title= 'Median Tips by Day of The Week')
p.set(xlabel= 'Day of the Week')
p.set(ylabel= 'Amount Tipped')
plt.show()
print()

#print a bar plot showing the relationship between party size and tip amount
p = sns.barplot(data = tips, x= 'size', y= 'tip', estimator = median)
p.set(title= 'Median Tips by Party Size')
p.set(xlabel= 'Party Size')
p.set(ylabel= 'Amount Tipped')
plt.show()
print()

#print a scatterplot showing party size and tip amount, colored by the sex of the server
p = sns.scatterplot(data = tips, x= 'day', y= 'tip', hue= 'sex')
p.set(title= 'Relationship Between Day of the Week and Tip Amount by Server Sex')
p.set(xlabel= 'Party Size')
p.set(ylabel= 'Amount Tipped')
plt.show()
print()

"""Insights from the desciptive statistics:

*   The mean amount tipped is 2.998279
*   The range of tips is 1-10
*   The average party size is 2.569672

Insights from the above histogram:

*   The distribution of tips is right skewed, this means that the mean tip amount will be higher than the median tip amount.

Insights from the Day of the Week bar plot:

*   Thursday has the lowest median tip amount
*   Friday and Sunday have the highest median tip amount

Insights from the Party Size bar plot:

*   Tips appear to be positivley correlated with party size
*   There is little increase in tip amount between a party of 5 and 6

Insights from the above scatterplot:

*   Male servers have the highest tip amounts for each day of the week
*   The highest tip for a male server is higher than the highest tip for a female server, though both were on Saturday  


"""

#create a forecasting (regression) model that only includes significant preditors of tip amount
model = smf.ols(formula= 'tip ~ total_bill', data = tips).fit()
print (model.summary())

"""I used the p-value of the overall model (prob (F-statistic)) to determine that the overall model is significant (as is it below 0.05). Then I used the individual p values (P>|t|) to determine if each independant variable was signigant, of which only total_bill was signifigant. The relationship for total bill is a positive relationship, which means that as total_bill increases (by 1 dollar) the tip amount will increase (by a forecasted 0.1050 dollars)."""

#forecast the tip amount given total_bill = 30.99
#save the coefficients to variables
print (model.params)
print()
intercept = model.params[0]
total_coef = model.params [1]

#save the test values to variables
total_x = 30.99

#generate a regression equation
forecasted_tip = total_coef * total_x + intercept

#print the forecast
print('The forecasted tip based on given test values:')
print(f'${forecasted_tip:,.2f}')

"""**Summary:**
I learned that you can forecast and explain tip amounts based the amount of the total bill because it is a signifigant independant variable (based on this data). I also learned that sex, smoker status, day of service, time of service, and party size are insignificant variables and cannot be relied upon to predict the tip amount.
"""