# -*- coding: utf-8 -*-
"""370_Mod_6_Videos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1twfeeWU1Z69xZ1sASNd0MCXFpBIxUCYm

Title: Forecasting and regression analysis
Description: This project covers forecasting and regression analysis that may affect the cash price of wheat
"""

import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

#read in the dataset, print the header and info
wheat = pd.read_csv("/content/wheat_cash_1963.csv")
print(wheat.head())
print()
print(wheat.info())
print()

#print the descriptive statistics
print(wheat.describe())
print()

#

#create a histogram of wheat prices
plt.hist(wheat['price'], bins=10)
plt.title('Distribution of wheat prices')
plt.ylabel('Frequency')
plt.xlabel('Price')
plt.show
print()

#create a scatterplot showing the relationship between economic growth and wheat price
plt.scatter(wheat['economic_growth'], wheat['price'])
plt.title('Relationship between economic growth and wheat price')
plt.ylabel('Price of wheat')
plt.xlabel('Economic Growth')
plt.show()

#Perform linear regression to help with forecasting using a library called statsmodels
#create the model with the dependant or outcome variable on the left and the independat/predictor variable on the right

#ols is a type of regression
#model = smf.ols(formula='outcome ~ predictor', data =dataframe).fit()
model = smf.ols(formula='price ~ economic_growth', data =wheat).fit()

#print the summary stats to view the results
print(model.summary())
print()

#f-statistic is the p value for the entire model
#p value is the possibility of the finding being due to error or randomness
#a p value less than 0.05 is statistically meaningful, may need to convert from scientific notation
#if meaningful you have a signifigant relationship between at least one independant variable and the dependant one

#intercept is always listed, under this are independant variables
#P>|t| is the independant variable for each variable, if there is one variable this is the same as above

#if coef is positive it indicates a positive relationship and vise versa
#the coef number means that when the independent variable (economic_growth) increases by 1 (in this case $1)
#price will increase by the number listed (.5016, or $0.50)

#R-squared, how much variance in price can be statistically attributed to economic growth, consider this as a percentage



#retrive coefficients and intercept
#params = paramaters which gives info about the model
intercept = model.params[0] #intercept is the first parameter in the list
coefficients = model.params

#print the intercept and coeffcients
print('Intercept', intercept)
print('Coefficients', coefficients[1])
print()
#print(model.params)

#forecast the cash price of wheat given an economic growth rate

#print the last 10 rows of economic growth to determine a test value
print(wheat['economic_growth'][-10:])
print()

#try a test value of 4.5
#calculate regression equation for this model (general: y=mx +b)
#y= the dependant value/outcome
#m= the coefficient
#x= test value
#b= intercept

#initialize variables to use in the equation
m = coefficients[1]
x = 3.3 #the test/input value
b = intercept

#create the specific equation for forecasting
predicted_wheat_price = m * x + b
print(f'Predicted wheat price when economic growth is {x}: ${predicted_wheat_price:,.2f}')
print()

#since we have a small dataset, we can print entire data to check our tets values
print(wheat)
print()

#check your predicted value against values in the dataset
#change your test(x) value to make different forecasts

"""Insights and Conclusions:


*   Economic growth is positivley correlated with the cash price of wheat, when growth increases, prices increase.
*   We should watch the economic growth indicator to determine what wheat pr


"""