# -*- coding: utf-8 -*-
"""370_Mod_6_Categorical.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PWSM5U5cgs6iIluHEkDZ9eeDHn5RVcbB
"""

#categorical variables are yes/no, true/false, or multiple choice answers
#quantitative variables are numerial (continuous, interval)

import pandas as pd
import statsmodels.formula.api as smf

#read in the data
sm= pd.read_csv("/content/social_media.csv")
print(sm.head())
print()

#the dependant variable is time spent

#create the model
#smf.ols(formula = dependant variable ~ indenpendant variable + independant variable)
model = smf.ols(formula = 'time_spent ~ age + indebt + gender', data = sm).fit()
print(model.summary())
#if the pvalue/f statistic is above 0.05, change the model (there are no signifigant variable in this one)
#just look at indebt true, if they are indebt then give the test value a 1, if not in debt a 0
#the value that is not listed in [] in the model for a two value test is the default/base value (female for gender)
#-.3662 for men means that as compared to a female (default value) has a reduction in time spent of
#in this model you cannot compare a non binary person with a male since the default is female

#equation for categorical values, you must create a new slot for every categorical value you see in the output
#y = m(age)*x(age) + m(indebt)*x(indebt) + m(gender_male)*x(gender_male) + m(gender_non)*x(gender_non)
#if they are not indebt the x(indebt) = 1
#if they are indebt the x(indebt) = 0
#for someone who is female:
#y = m(age)*x(age) + m(indebt)*x(indebt) + m(gender_male)*0 + m(gender_non)*0
#for someone who is non-binary:
#y = m(age)*x(age) + m(indebt)*x(indebt) + m(gender_male)*0 + m(gender_non)*1

gender_m_coeff = model.params
gender_m_x